### ISSUE TITLE
Support of agent-js with bigger frameworks like nestjs

### ISSUE THREAD

**Issue by haayhappen** [livekit/agents-js#121]
Hey guys,

I appreciate the effort you put into this, enabling OpenAIs realtime API at such early stage.

Quick question:
What would be the ideal way to integrate this into a bigger framework, say NestJs?

It currently looks like the preferred approach is to start this via its own node process to access the worker CLI.
There are two problems I'm currently facing:

1. I already have a node process running (ideally including the dynamic agent config), namely the nest server (might be possible to enable this via subprocesses?)
2. I might not have the agent available at startup time eg.: if I want to let the app user configure behavioral aspects of the agent.

I'd appreciate any guidance!

**Comment by leethree** [comment]
yes would like the ability to run LiveKit programatically instead of CLI.

**Comment by nbsp** [comment]
it is possible to run your worker programmatically! `cli.runApp` is a simple CLI wrapper on top of `new Worker(new WorkerOptions(...))`. you can feed whatever options whenever you want and simply start the worker without using CLI.
