### ISSUE TITLE
Consider using tsup to bundle

### ISSUE THREAD

**Issue by martin-purplefish** [livekit/agents-js#157]
https://github.com/egoist/tsup

I think it'd make things a lot cleaner - it'd mean you don't have to import .js files, you can do import prefixes (e.g. @/agent/foo' instead of '../agent/foo.js' stuff.

**Comment by nbsp** [comment]
interesting! do you know if it'd still work with tsx without transpiling?

**Comment by martin-purplefish** [comment]
I don't know - but it _should_ since it's just bundling things using (mostly) your tsconfig - so I would expect tsx to work fine.

**Comment by nbsp** [comment]
when we merge CJS support to node-sdks, i'll set up tsup here to transpile the TypeScript to both standards so we have a true dual package.

**Comment by martin-purplefish** [comment]
Cool! Happy to help!
