### ISSUE TITLE
Error when running silero VAD from npm package

### ISSUE THREAD

**Issue by wezerr** [livekit/agents-js#163]
I'm encountering an issue while trying to run the Silero VAD from the npm package. The following error message is displayed:

`Error: Load model from C:/Projects/node-agent/node_modules/.pnpm/@livekit+agents-plugin-silero@0.4.4/node_modules/@livekit/agents-plugin-silero/dist/`

**Comment by nbsp** [comment]
this seems to be an issue specific to Windows, will look into it further
