### ISSUE TITLE
Multimodel Agent to support `user_speech_committed` and `agent_speech_committed` events

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents-js#164]
Currently they are supported on Python but not Node yet.

**Comment by nbsp** [comment]
user speech committed is trivial, but agent speech committed depends on #99

**Comment by creightontaylor** [comment]
We need this for transcriptions because the user can send written chat messages (outside of LiveKit) as well. It's the last remaining piece before we can start testing with users. The entire app built around it, including accepting payments, is done (at least in MVP form). Would love this ASAP.
