### ISSUE TITLE
Empty assistant messages in context in VoicePipelineAgent

### ISSUE THREAD

**Issue by MattSkala** [livekit/agents-js#204]
It seems the messages generated by LLM are not added to the context. When logging `ctx.messages` in `beforeLLMCallback`, I can see there are all user's messages (role = 1), but all assistant messages (role = 2) only contain an empty string in the content field.

Environment:
@livekit/agents v0.5.0

Agent setup:

```typescript
new pipeline.VoicePipelineAgent(
    ctx.proc.userData.vad! as silero.VAD,
    openai.STT.withGroq({ detectLanguage: true }),     
    new openai.LLM({ model: 'gpt-4o', temperature: 0.7 }),
    new openai.TTS({ voice: 'onyx' }),
    {
        beforeLLMCallback: (_, ctx) => {
            console.log(ctx.messages)
        },
    }
)
```

Output

```
[
    {
        "role": 0,
        "content": "You are a helpful assistant"
    },
    {
        "role": 2,
        "content": ""
    },
    {
        "role": 1,
        "content": " Hey, how are you doing?"
    },
    {
        "role": 2,
        "content": ""
    },
    {
        "role": 1,
        "content": " I'm fine, thanks."
    }
]
```

**Comment by nbsp** [comment]
i reckon is a side-effect of transcriptions not being fully implemented just yet for VoicePipelineAgent. we're working on it, and it'll be available in the next minor release

**Comment by valdrox** [comment]
Thanks guys, super fast turnaround. I can confirm the issue is resolved!

**Comment by davidzhao** [comment]
thanks for the confirmation @valdrox!

**Comment by MattSkala** [comment]
Thanks, the issue is resolved
